In [1]:
import numpy as np
np.__version__    # command to check the version of package installed

'1.23.5'

In [2]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [4]:
mearray = ([range(i, i + 3) for i in [2, 4, 6]])
for row in mearray:
        for col in row:
            print(col, end="")
        print("\n")

234

456

678



In [5]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.62371286, 0.78170699, 0.62898366],
       [0.63928319, 0.11778907, 0.49672177],
       [0.17005025, 0.33948074, 0.80624511]])

In [8]:
np.random.seed(0)  # seed for reproducability

def compute_reciprocals(values):
    output = np.empty(len(values))  # create an empty array of same length as input array 
    for i in range(len(values)):
        output[i] = 1.0 / values[i]  # perform reciprocal operation within for loop
    return output
        
values = np.random.randint(1, 10, size=5)  # 1D array of length 5 with values between 1 to 10
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [9]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]


In [10]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

171 ms ± 6.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.22 ms ± 396 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [11]:
min(big_array), max(big_array)

(7.071203171893359e-07, 0.9999997207656334)

In [12]:
np.min(big_array), np.max(big_array)

(7.071203171893359e-07, 0.9999997207656334)